- apt_key: url=https://packages.sury.org/php/apt.gpg

- apt_repository:
    filename: php-fpm
    repo: deb https://packages.sury.org/php/ buster main

- name: Installing packages
  apt:
    pkg:
    - php{{ php_version }}-fpm
    - php{{ php_version }}-cli
    - php{{ php_version }}-dev
    - php{{ php_version }}-bz2
    - php{{ php_version }}-curl
    - php{{ php_version }}-gd
    - php{{ php_version }}-mysql
    - php{{ php_version }}-sqlite3
    - php{{ php_version }}-zip

- alternatives: name=php path=/usr/bin/php{{ php_version }}
- alternatives: name=phpize path=/usr/bin/phpize{{ php_version }}
- alternatives: name=php-config path=/usr/bin/php-config{{ php_version }}

- lineinfile: path=/etc/php/7.4/fpm/php.ini regexp='^display_errors = Off$' line='display_errors=On'
- lineinfile: path=/etc/php/7.4/fpm/php.ini regexp='^;cgi.fix_pathinfo=1$' line='cgi.fix_pathinfo=0'

- file: path=/run/php state=directory

- service: name=php{{ php_version }}-fpm state=started